### ISSUE TITLE
Extract files in a zip to root of a folder?

### ISSUE THREAD

**Issue by slier81** [mmoreram/extractor#7]
I have a zip file uploaded to server for automated extract.

the zip file construction is like this:

> /file.zip/folder1/image1.jpg
> /file.zip/folder1/image2.jpg
> /file.zip/folder1/image3.jpg

$specificDirectory = new SpecificDirectory( '/images/upload/' );
$extensionResolver = new ExtensionResolver;
$extractor = new Extractor( $specificDirectory, $extensionResolver );
$archive_list = $extractor->extractFromFile( $destination_file );

But by using the function `extractFromFile`, it will extract to `/images/upload` as ff:

> /images/upload/folder1/image1.jpg
> /images/upload/folder1/image2.jpg
> /images/upload/folder1/image3.jpg

Is there any way to extract the files in folder1 to the root of myFolder?

Ideal:

> /images/upload/image1.jpg
> /images/upload/image2.jpg
> /images/upload/image3.jpg

**Comment by mmoreram** [comment]
Yes.
After extracting your files under /folder1, move all content inside to the place you need :)
