### ISSUE TITLE
Adapter "Rar" is currenly not available. Please check if you have the needed php extension installed in your php.ini

### ISSUE THREAD

**Issue by slier81** [mmoreram/extractor#8]
Im getting this error: `Adapter "Rar" is currenly not available. Please check if you have the needed php extension installed in your php.ini`

I already install rar extension, yet your library still insist saying that i dont install rar extension.

Please help

**Comment by mmoreram** [comment]
Can you check that, please?

https://github.com/mmoreram/extractor/blob/master/src/Extractor/Adapter/RarExtractorAdapter.php#L44

**Comment by slier81** [comment]
@mmoreram Yep, somehow i dont have access to `\RarArchive`

Probably there is something wrong with my `rar` extension installation

**Comment by mmoreram** [comment]
Probably...

**Comment by slier81** [comment]
Turn out im running the script through the cli but i only configure `rar` extension in php.ini for apache and not for cli
